name: Schedule Deploy Documentation

on:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches:
      - main
      - dev-mdbook
  repository_dispatch:
    types: [deploy-doc]

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Setup mdbook-admonish
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: tommilligan/mdbook-admonish
          tag: v1.15.0
          cache: enable

      - name: Setup mdbook-toc
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: badboy/mdbook-toc
          tag: 0.14.2
          cache: enable

      - name: Setup mdbook-tera
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: avitex/mdbook-tera
          tag: v0.5.1
          cache: enable

      - name: mdBook build
        run: |
          make build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev-mdbook'}}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book